name: Generate SBOM

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    sbom:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, json, libxml
                  tools: composer:v2

            - name: Install Composer dependencies
              run: composer install --no-interaction --no-progress

            - name: Allow CycloneDX plugin
              run: composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true

            - name: Install CycloneDX Composer plugin
              run: composer global require cyclonedx/cyclonedx-php-composer

            - name: Generate SBOM (CycloneDX XML)
              run: composer CycloneDX:make-sbom --output-format=XML --output-file=sbom.xml

            - name: Upload SBOM artifact
              uses: actions/upload-artifact@v4
              with:
                  name: sbom
                  path: sbom.xml
